### ISSUE TITLE
How can i handle multiple connection, with different ip and different ports ?

### ISSUE THREAD

**Issue by emulk** [maximegris/node-websockify#15]
I need to handel the connection on different servers, is possible to open different connection, with like 5 different servers, like:

websockifyMaker({
    source: '127.0.0.1:8081',
    target: 'remoteServerIp:5901'
}, {
    source: '127.0.0.1:8082',
    target: 'remoteServerIp:5902'
}, {
    source: '127.0.0.1:8083',
    target: 'remoteServerIp:5903'
}

);

Thank you

**Comment by Craigzyc** [comment]
You can just make multiple instances

```
let websockify = []
websockify[0] = require('@maximegris/node-websockify');
websockify[1] = require('@maximegris/node-websockify');
websockify[2] = require('@maximegris/node-websockify');

websockify[0]({
    source: '127.0.0.1:8081',
    target: 'remoteServerIp:5901'
});

websockify[1]({
    source: '127.0.0.1:8082',
    target: 'remoteServerIp:5902'
});

websockify[2]({
    source: '127.0.0.1:8083',
    target: 'remoteServerIp:5903'
});
```

**Comment by sukkamehu** [comment]
@emulk https://github.com/sukkamehu/node-multi-websockify Just moment ago I created probably something which you could utilize?

**Comment by mirkoboggian** [comment]
> You can just make multiple instances
> 
> ```
> let websockify = []
> websockify[0] = require('@maximegris/node-websockify');
> websockify[1] = require('@maximegris/node-websockify');
> websockify[2] = require('@maximegris/node-websockify');
> 
> websockify[0]({
>     source: '127.0.0.1:8081',
>     target: 'remoteServerIp:5901'
> });
> 
> websockify[1]({
>     source: '127.0.0.1:8082',
>     target: 'remoteServerIp:5902'
> });
> 
> websockify[2]({
>     source: '127.0.0.1:8083',
>     target: 'remoteServerIp:5903'
> });
> ```

Hi, it doens't work.

`WebSocket settings:
    - proxying from 127.0.0.1:8001 to 10.233.0.89:5900
    - Running in unencrypted HTTP (ws://) mode
no callbacks
WebSocket settings:
    - proxying from 127.0.0.1:8002 to 10.233.0.104:5900
    - Running in unencrypted HTTP (ws://) mode
C:\Websockify\node_modules\ws\lib\websocket-server.js:83
        throw new Error(
        ^

Error: The HTTP/S server is already being used by another WebSocket server
    at new WebSocketServer (C:\Websockify\node_modules\ws\lib\websocket-server.js:83:15)
    at Server.<anonymous> (C:\Websockify\node_modules\@maximegris\node-websockify\websockify.js:199:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitListeningNT (node:net:1785:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.17.1`

**Comment by mirkoboggian** [comment]
> I need to handel the connection on different servers, is possible to open different connection, with like 5 different servers, like:
> 
> websockifyMaker({ source: '127.0.0.1:8081', target: 'remoteServerIp:5901' }, { source: '127.0.0.1:8082', target: 'remoteServerIp:5902' }, { source: '127.0.0.1:8083', target: 'remoteServerIp:5903' }
> 
> );
> 
> Thank you

did you solve?
